<?php

/**
 * Implements hook_mail_alter().
 */
function mail_alter_headers_mail_alter(&$message) {
  //dpm($message['key']);
  switch ($message['key']) {
    case 'page_mail':
 	  //dpm($message['headers']);
      //$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
	  $message['headers']['Return-Path'] = 'user@email.com';
	  $message['headers']['Sender'] = 'user@email.com';
	  $message['headers']['From'] = 'Site name';
	  $message['headers']['Reply-to'] = 'user@email.com';          
	  
	  //dpm($message);
	  $message['subject'] = $message['subject'] . ' - site name';
      break;
  }
}
